-- AlterTable
ALTER TABLE "courts" ALTER COLUMN "amenities" DROP NOT NULL,
ALTER COLUMN "amenities" DROP DEFAULT,
ALTER COLUMN "amenities" SET DATA TYPE TEXT,
ALTER COLUMN "photos" DROP NOT NULL,
ALTER COLUMN "photos" DROP DEFAULT,
ALTER COLUMN "photos" SET DATA TYPE TEXT;
